### ISSUE TITLE
New version won't publish to rubygems

### ISSUE THREAD

**Issue by hieubui149** [Asana/ruby-asana#120]
I saw we released `v0.10.9` in this repo but the maximum version in rubygems.org remains at `v0.10.3`. Can you help check the release bot?
### Captured from Rubygems
![Screen Shot 2021-10-27 at 16 19 59](https://user-images.githubusercontent.com/7339379/139037689-11ce5fc9-ec76-430e-90fd-65f519fe3fe7.png)

**Comment by mishina2228** [comment]
Hi, any updates on it?
`v0.10.10` is released on [GitHub Releases](https://github.com/Asana/ruby-asana/releases), but not in [rubygems.org](https://rubygems.org/gems/asana) yet.

[`.travis.yml`](https://github.com/Asana/ruby-asana/blob/d2ba0fe6cd0b1e9e9012ebe446e841a7fcaf68e7/.travis.yml) has a section related with gem publish, 
but the building on [travis-ci.org](https://travis-ci.org/) is ceased since June 15th, 2021.
I think this is why new gems are not being released.

@aw-asana
Would you consider migrating to travis-ci.com or any other CI platform? (e.g. GitHub Actions)
Thanks!

**Comment by mishina2228** [comment]
Ah, migrating from Travis to GitHub Actions seems to be done in #133!
Hopefully a new gem will be released on rubygems.org when next version bumped!

**Comment by igor-alexandrov** [comment]
@jv-asana John, this one should be closed.
