### ISSUE TITLE
expand tasks doesn't seem to work!

### ISSUE THREAD

**Issue by epugh** [Asana/ruby-asana#46]
I am trying to avoid querying Asana while cloning a project Template, so was thinking the expand would let me avoid lots of calls back to get each task.

I'm trying:
```
client.projects.find_by_id(project_id, options: { expand: ['tasks'] })
```

But not getting any errors, or expanded tasks!
Thoughts?

**Comment by epugh** [comment]
Doing this did work, but does seem awkward!

```
sip_project_template.tasks(options: { fields: ['name','assignee','notes','followers'] })
```

**Comment by slobak** [comment]
Sorry you experienced some confusion with the options. If you look in the "selecting fields" section of the documentation of [I/O Options](https://asana.com/developers/documentation/getting-started/input-output-options), you'll note that if you want to expand the root objects being returned, the path to provide is `this`. There is no field named `tasks` which is why your expansion did not work.

Note also that expansion and individual field selection cannot be used together—expansion is just a convenient way of getting the whole record for one type of object.
