### ISSUE TITLE
ruby-asana not updated with the fix for user find_by_id

### ISSUE THREAD

**Issue by saagar** [Asana/ruby-asana#48]
This was commited to the api meta, but the api-meta-incoming doesn't seem to have been updated (or passing) for a while.
https://github.com/Asana/asana-api-meta/commit/14a6e6cc09775f295e55bbf97beb601dd622887f

We wanted to use find_by_id in a project we're hacking on :slightly_smiling_face:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694763484872/182694840288231)

**Comment by praecipula** [comment]
Hi Saagar,

You're right, it has been quite a while since we've updated the client libraries from `asana-api-meta`. The good news is that I'm working on this right now, and we should very soon have not only updated git repos, but updated packages as well - in Ruby's case, an updated gem. When that happens, I'll close this issue, so keep an eye out!

Thanks,
-Matt
