### ISSUE TITLE
Add gid attributes to resources with an id attribute

### ISSUE THREAD

**Issue by spadachris** [Asana/ruby-asana#67]
based on https://asana.com/developers/news/string-ids it would be nice to have all resources with `id`s to have their corresponding `gid`s add to the objects.

**Comment by rossgrambo** [comment]
Thank you! I'll ensure this is included when we deploy the client libraries next week.

**Comment by spadachris** [comment]
@rossgrambo thank you

**Comment by spadachris** [comment]
@rossgrambo is there any ETA on when the client libraries will be updated?

**Comment by rossgrambo** [comment]
The PRs for the other client libraries are out. Ruby requires some extra attention. It should be ready soon!

**Comment by crwenner** [comment]
I noticed the PR that adds `gid` (https://github.com/Asana/ruby-asana/pull/70) has been merged. When will this new version (0.9.0) get pushed to ruby gems?

**Comment by rossgrambo** [comment]
Thank you @crwenner! I was not aware that the release didn't make it to ruby gems. It looks like our automated deploy failed to push it from github to ruby gems. We just found the issue and are working to resolve it now.

In the meantime you could install the 0.9.0 gem from this repo. I'll post here when it's resolved.

**Comment by crwenner** [comment]
@rossgrambo It appears there are a few bugs with using the new version of this gem and trying to use `gid`. For example, I am trying to find the associated tags on a specific task only using `gid`. However, due to the tags method in [the task resource](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/task.rb#L420) forcing the use if id, this is not possible.

This is also affecting [Task#projects](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/task.rb#L366), [Task#subtasks](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/task.rb#L449), [Task#stories](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/task.rb#L487), and more just in the `Task` class.

This is not localized to Task, as you can see by [Project#tasks](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/project.rb#L236).

This also appears to be affecting action methods like [Task#update](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/project.rb#L193), [Task#delete](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/project.rb#L202), etc.

**Comment by rossgrambo** [comment]
This was an oversight on my part. I just merged in a patch to resolve this. Thank you @crwenner for pinging me, and please let me know if you find any other issues.

**Comment by amandapuff** [comment]
@rossgrambo I noticed in your latest [pull request](https://github.com/Asana/ruby-asana/pull/72) that `id` is no longer supported. We can still use `id` if we've opted out of the `string_ids` feature with the `Asana-Disable` header. Can we please have support for either `id` or `gid` going forward until `id` is removed from the API?

**Comment by rossgrambo** [comment]
@amandapuff , the changes cause a number of commands to use the gid field instead of the id when making requests. This should be backwards compatible, as your object should still have the gid field. 

Do you have an example of an issue / which method you're calling?

**Comment by amandapuff** [comment]
@rossgrambo, I apologize, we did some testing this morning and haven't run into any issues with opting in or out of the `string_ids` feature. Thank you for the quick response and the quick bug fix!

**Comment by rossgrambo** [comment]
I'm going to close this for now, but please comment here or open another issue if you have any problems!
