### ISSUE TITLE
Any plans to release new version containing latest changes to asana-api-meta?

### ISSUE THREAD

**Issue by garethcokell** [Asana/ruby-asana#71]
I'm specifically after the ability to duplicate a project, but I imagine that it would be useful to release a new version of this gem each time a change is made to asana-api-meta? Can this be automated?

**Comment by rossgrambo** [comment]
Hey @garethcokell,

There's a PR out now to get you that functionality. It should be completed within the next week or so.

We're working to restore automated updates. This use to be the way things worked. More and more one-off changes had to be made to the generated code in order for it to be ready to use because of misc. edge cases. It's got to a point now where we're investing time into fixing this, and the tooling will keep things in sync. 👍
